version: "3"

services:
    db:
        image: mongo
        ports:
            - "${DB_PORT}:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        volumes:
            - ./data:/data/db
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
